import './globals.css';
import Header from '@/components/header/page.jsx';

export const metadata = {
  title: 'Onkar Patel — Web Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
